import { Octokit } from '@octokit/rest';
import type { NewDevice } from '../types.js';
import { TARGET_FILE_PATH, PREVIOUS_YEAR_FILE_PATH, REPO_OWNER, REPO_NAME, CURRENT_YEAR, GSM_ARENA_SAMSUNG_URL } from '../config.js';

export async function fetchCurrentFile(
  octokit: Octokit,
): Promise<{ content: string; sha: string } | null> {
  try {
    const res = await octokit.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: TARGET_FILE_PATH });
    const file = res.data as { content: string; sha: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content, sha: file.sha };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

export async function fetchPreviousYearFile(
  octokit: Octokit,
): Promise<{ content: string } | null> {
  try {
    const res = await octokit.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: PREVIOUS_YEAR_FILE_PATH });
    const file = res.data as { content: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

function deviceSummary(devices: NewDevice[], max = 2): string {
  const names = devices.map((d) => d.name);
  if (names.length <= max) return names.join(', ');
  return `${names.slice(0, max).join(', ')} and ${names.length - max} more`;
}

function formatDeviceSection(devices: NewDevice[]): string {
  const typeLabel: Record<string, string> = { phone: '📱 Phones', tablet: '📟 Tablets', watch: '⌚ Watches' };
  const groups: Record<string, NewDevice[]> = {};
  for (const d of devices) {
    (groups[d.type] ??= []).push(d);
  }
  return Object.entries(groups)
    .map(([type, group]) => {
      const header = typeLabel[type] ?? type;
      const rows = group
        .map((d) => {
          const models = d.models.length > 0 ? `\n  - Models: \`${d.models.join('`, `')}\`` : '';
          return `- **${d.name}** — released \`${d.releaseDate}\`${models}`;
        })
        .join('\n');
      return `#### ${header}\n\n${rows}`;
    })
    .join('\n\n');
}

export async function createPR(
  octokit: Octokit,
  updatedContent: string,
  fileSha: string | null,
  newDevices: NewDevice[],
): Promise<string> {
  const date = new Date().toISOString().split('T')[0];
  const branch = `feat/sync-devices-${date}`;

  const repoData = await octokit.repos.get({ owner: REPO_OWNER, repo: REPO_NAME });
  const defaultBranch = repoData.data.default_branch;

  const refData = await octokit.git.getRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `heads/${defaultBranch}` });
  const latestCommitSha = refData.data.object.sha;

  try {
    await octokit.git.createRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `refs/heads/${branch}`, sha: latestCommitSha });
    console.log(`   Branch created: ${branch}`);
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 422) {
      await octokit.git.updateRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `heads/${branch}`, sha: latestCommitSha, force: true });
      console.log(`   Branch already existed, reset to latest: ${branch}`);
    } else {
      throw err;
    }
  }

  const summary = deviceSummary(newDevices);

  await octokit.repos.createOrUpdateFileContents({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: TARGET_FILE_PATH,
    message: `feat: add ${summary} for ${CURRENT_YEAR}`,
    content: Buffer.from(updatedContent).toString('base64'),
    branch,
    ...(fileSha ? { sha: fileSha } : {}),
  });
  console.log(`   File committed to branch`);

  const pr = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `feat: sync ${summary} for ${CURRENT_YEAR}`,
    head: branch,
    base: defaultBranch,
    body: `## Samsung Device Sync — ${date}

Automatically generated by the GSM Arena sync agent.

### New devices added (${newDevices.length})

${formatDeviceSection(newDevices)}

---
*Source: [GSM Arena Samsung listings](${GSM_ARENA_SAMSUNG_URL})*
*File updated: \`${TARGET_FILE_PATH}\`*`,
  });

  return pr.data.html_url;
}
