import { Octokit } from '@octokit/rest';
import type { NewDevice } from '../types.js';
import { TARGET_FILE_PATH, PREVIOUS_YEAR_FILE_PATH, REPO_OWNER, REPO_NAME, CURRENT_YEAR, GSM_ARENA_SAMSUNG_URL } from '../config.js';

export async function fetchCurrentFile(
  octokit: Octokit,
): Promise<{ content: string; sha: string } | null> {
  try {
    const res = await octokit.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: TARGET_FILE_PATH });
    const file = res.data as { content: string; sha: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content, sha: file.sha };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

export async function fetchPreviousYearFile(
  octokit: Octokit,
): Promise<{ content: string } | null> {
  try {
    const res = await octokit.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: PREVIOUS_YEAR_FILE_PATH });
    const file = res.data as { content: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

export async function createPR(
  octokit: Octokit,
  updatedContent: string,
  fileSha: string | null,
  newDevices: NewDevice[],
): Promise<string> {
  const date = new Date().toISOString().split('T')[0];
  const branch = `feat/sync-devices-${date}`;

  const repoData = await octokit.repos.get({ owner: REPO_OWNER, repo: REPO_NAME });
  const defaultBranch = repoData.data.default_branch;

  const refData = await octokit.git.getRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `heads/${defaultBranch}` });
  const latestCommitSha = refData.data.object.sha;

  await octokit.git.createRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `refs/heads/${branch}`, sha: latestCommitSha });
  console.log(`   Branch created: ${branch}`);

  await octokit.repos.createOrUpdateFileContents({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    path: TARGET_FILE_PATH,
    message: `feat: add ${newDevices.length} new Samsung device(s) for ${CURRENT_YEAR}`,
    content: Buffer.from(updatedContent).toString('base64'),
    branch,
    ...(fileSha ? { sha: fileSha } : {}),
  });
  console.log(`   File committed to branch`);

  const deviceList = newDevices
    .map((d) => `- **${d.name}** (${d.type}) — \`${d.releaseDate}\` — models: ${d.models.join(', ') || 'N/A'}`)
    .join('\n');

  const pr = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `feat: sync ${newDevices.length} new Samsung device(s) for ${CURRENT_YEAR}`,
    head: branch,
    base: defaultBranch,
    body: `## Samsung Device Sync — ${date}

Automatically generated by the GSM Arena sync agent.

### New devices added (${newDevices.length})

${deviceList}

---
*Source: [GSM Arena Samsung listings](${GSM_ARENA_SAMSUNG_URL})*
*File updated: \`${TARGET_FILE_PATH}\`*`,
  });

  return pr.data.html_url;
}
