import { Octokit } from '@octokit/rest';
import type { NewDevice } from '../agent/schema.js';
import {
  TARGET_FILE_PATH,
  PREVIOUS_YEAR_FILE_PATH,
  REPO_OWNER,
  REPO_NAME,
  CURRENT_YEAR,
  GSM_ARENA_SAMSUNG_URL,
} from '../config.js';

export async function fetchCurrentFile(
  octokit: Octokit,
): Promise<{ content: string; sha: string } | null> {
  try {
    const res = await octokit.repos.getContent({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      path: TARGET_FILE_PATH,
    });
    const file = res.data as { content: string; sha: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content, sha: file.sha };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

export async function fetchPreviousYearFile(octokit: Octokit): Promise<{ content: string } | null> {
  try {
    const res = await octokit.repos.getContent({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      path: PREVIOUS_YEAR_FILE_PATH,
    });
    const file = res.data as { content: string };
    const content = Buffer.from(file.content, 'base64').toString('utf-8');
    return { content };
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 404) return null;
    throw err;
  }
}

function deviceSummary(devices: NewDevice[], max = 2): string {
  const names = devices.map((d) => d.name);
  if (names.length <= max) return names.join(', ');
  return `${names.slice(0, max).join(', ')} and ${names.length - max} more`;
}

function formatDeviceSection(devices: NewDevice[]): string {
  const typeLabel: Record<string, string> = {
    phone: '📱 Phones',
    tablet: '📟 Tablets',
    watch: '⌚ Watches',
  };
  const groups: Record<string, NewDevice[]> = {};
  for (const d of devices) {
    (groups[d.type] ??= []).push(d);
  }
  return Object.entries(groups)
    .map(([type, group]) => {
      const header = typeLabel[type] ?? type;
      const rows = group
        .map((d) => {
          const models = d.models.length > 0 ? `\n  - Models: \`${d.models.join('`, `')}\`` : '';
          return `- **${d.name}** — released \`${d.releaseDate}\`${models}`;
        })
        .join('\n');
      return `#### ${header}\n\n${rows}`;
    })
    .join('\n\n');
}

export interface CommitFile {
  path: string;
  content: string;
}

export async function createPR(
  octokit: Octokit,
  files: CommitFile[],
  newDevices: NewDevice[],
): Promise<string> {
  const date = new Date().toISOString().split('T')[0];
  const branch = `feat/sync-devices-${date}`;
  const summary = deviceSummary(newDevices);

  const repoData = await octokit.repos.get({ owner: REPO_OWNER, repo: REPO_NAME });
  const defaultBranch = repoData.data.default_branch;

  const refData = await octokit.git.getRef({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    ref: `heads/${defaultBranch}`,
  });
  const latestCommitSha = refData.data.object.sha;

  // Commit every file (data file + regenerated src/generated) as one commit via the Git Data API:
  // a blob per file, a tree layered on the base commit's tree, then a commit and a branch ref.
  const baseCommit = await octokit.git.getCommit({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    commit_sha: latestCommitSha,
  });

  const tree = await Promise.all(
    files.map(async (file) => {
      const blob = await octokit.git.createBlob({
        owner: REPO_OWNER,
        repo: REPO_NAME,
        content: Buffer.from(file.content).toString('base64'),
        encoding: 'base64',
      });
      return {
        path: file.path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.data.sha,
      };
    }),
  );

  const newTree = await octokit.git.createTree({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    base_tree: baseCommit.data.tree.sha,
    tree,
  });

  const commit = await octokit.git.createCommit({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    message: `feat: add ${summary} for ${CURRENT_YEAR}`,
    tree: newTree.data.sha,
    parents: [latestCommitSha],
  });

  try {
    await octokit.git.createRef({
      owner: REPO_OWNER,
      repo: REPO_NAME,
      ref: `refs/heads/${branch}`,
      sha: commit.data.sha,
    });
    console.log(`   Branch created: ${branch}`);
  } catch (err: unknown) {
    if ((err as { status?: number }).status === 422) {
      await octokit.git.updateRef({
        owner: REPO_OWNER,
        repo: REPO_NAME,
        ref: `heads/${branch}`,
        sha: commit.data.sha,
        force: true,
      });
      console.log(`   Branch already existed, reset to new commit: ${branch}`);
    } else {
      throw err;
    }
  }
  console.log(`   Committed ${String(files.length)} file(s) to branch`);

  const pr = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `feat: sync ${summary} for ${CURRENT_YEAR}`,
    head: branch,
    base: defaultBranch,
    body: `## Samsung Device Sync — ${date}

Automatically generated by the GSM Arena sync agent.

### New devices added (${newDevices.length})

${formatDeviceSection(newDevices)}

---
*Source: [GSM Arena Samsung listings](${GSM_ARENA_SAMSUNG_URL})*
*Updated \`${TARGET_FILE_PATH}\` and regenerated \`src/generated/*\`.*`,
  });

  return pr.data.html_url;
}
